SELECT
    PM.DT_PRE_MED,
    ATE.CD_ATENDIMENTO,
    PAC.DT_NASCIMENTO,
    CASE
        WHEN DBAMV.FN_IDADE(PAC.DT_NASCIMENTO) > 60 THEN 'IDOSO'
        WHEN DBAMV.FN_IDADE(PAC.DT_NASCIMENTO) < 16 THEN 'CRIANCA'
        ELSE 'ADULTO'
    END FAIXA_ETARIA,    
    DBAMV.FN_IDADE(PAC.DT_NASCIMENTO) IDADE,
    PAC.TP_SEXO,
    TA.CD_TIPO_INTERNACAO,
    TA.DS_TIPO_INTERNACAO,
    SE.CD_SERVICO,
    SE.DS_SERVICO,
    TP.DS_TIP_PRESC
FROM
    PRE_MED PM 
    INNER JOIN ITPRE_MED IPM        ON PM.CD_PRE_MED=IPM.CD_PRE_MED AND IPM.CD_TIP_ESQ = 'DEV'
    INNER JOIN TIP_PRESC TP         ON IPM.CD_TIP_PRESC=TP.CD_TIP_PRESC 
    INNER JOIN ATENDIME ATE         ON ATE.CD_ATENDIMENTO=PM.CD_ATENDIMENTO
    INNER JOIN PACIENTE PAC         ON ATE.CD_PACIENTE=PAC.CD_PACIENTE
    INNER JOIN TIPO_INTERNACAO TA   ON TA.CD_TIPO_INTERNACAO = ATE.CD_TIPO_INTERNACAO
    INNER JOIN SERVICO SE           ON SE.CD_SERVICO=ATE.CD_SERVICO
WHERE 
    PM.DT_PRE_MED BETWEEN '01/01/2024' AND '30/01/2024'
    AND PM.CD_PRE_MED IN ( --SELECIONA AS PRIMEIRAS PRESCRICOES COM DEV DE CADA ATENDIMENTO
                            SELECT
                                MIN(PM1.CD_PRE_MED)
                            FROM 
                                DBAMV.ITPRE_MED IPM1
                                INNER JOIN PRE_MED PM1 ON PM1.CD_PRE_MED=IPM1.CD_PRE_MED
                            WHERE
                                IPM1.CD_TIP_ESQ = 'DEV'
                            GROUP BY PM1.CD_ATENDIMENTO
                        )
;